### ISSUE TITLE
Report total daily income

### ISSUE THREAD

**Issue by latetot** [eth2353/ETHstaker.tax#14]
Hi - I love your site-its so helpful.  When you run a query for multiple validators, would you consider an option for the "download CSV of daily rewards for all validators" to aggregate the amounts by day for e.g. ETH income, USD income, validator balances (similar to the way the site displays the income per day on the bar chart)?  Right now it list each validator separately for each day, but for most tax reporting tools its easier just to have one total amount of ETH/USD income per day and I can't find an easy way to aggregate manually after downloading.  Thanks a lot!

**Comment by eth2353** [comment]
Hey,

Sure, that sounds like a good improvement, I added a checkbox that allows you to group the data by date. Check it out, let me know if this is what you meant!

**Comment by davidkassa** [comment]
This checkbox works great! What about an additional column for combined income? I can massage the data but it'd be nice.

**Comment by eth2353** [comment]
You mean adding a column which sums the consensus and execution layer income? I don't know about that. If you need it combined it's very easy to just sum those two columns?

**Comment by davidkassa** [comment]
Yes, I imagine users either need the consensus layer only because they are monitoring execution income via an address monitor or something or they want both combined since combined, daily total is what’s needed for tax basis. On Feb 19, 2023, at 4:33 AM, eth2353 ***@***.***> wrote:﻿
You mean adding a column which sums the consensus and execution layer income? I don't know about that. If you need it combined it's very easy to just sum those two columns?

**Comment by latetot** [comment]
> Hey,
> 
> Sure, that sounds like a good improvement, I added a checkbox that allows you to group the data by date. Check it out, let me know if this is what you meant!

This is perfect - thank you so much!
