### ISSUE TITLE
Incorrectly showing negative earnings on validators when including the current date

### ISSUE THREAD

**Issue by slavik0329** [eth2353/ETHstaker.tax#19]
Noticed a bug where the final date has negative incomes for some validators for current date.This is related to the withdrawals that were just enabled. The calculation incorrectly includes withdrawals as losses.

**Comment by eth2353** [comment]
Thanks for reporting this, I thought I had a bit more time to figure out how to address withdrawals. But since the calculation of consensus layer income is based solely on the validator balance difference, this will show incorrect values for every day during which a withdrawal occurred...

I added an alert to the website for now and will be working on fixing this ASAP.

**Comment by ksheni56** [comment]
Thank you. @eth2353

**Comment by eth2353** [comment]
This should now be fixed, let me know if I overlooked some edge case but from some manual testing it seems to be fine.

I've also added a separate column to the output CSV that contains the amount withdrawn. This way you can choose to use that data and ignore the consensus layer income, since you only technically gain dominion over it once the ETH is withdrawn.

**Comment by slavik0329** [comment]
@eth2353 It's working!
